import logging
#
# def pytest_runtest_call(__multicall__):
#     try:
#         __multicall__.execute()
#     except KeyboardInterrupt:
#         raise
#     except:
#         logging.exception('pytest_runtest_call caught exception:')
#         raise


